---
- name: Copy /etc/network/interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reload networking

- name: Copy Quagga Configuration
  template:
    src: Quagga.conf.j2
    dest: /etc/quagga/Quagga.conf
  notify: reload quagga

- name: Install Python pip
  apt:
    name: python-pip
    state: present

- name: Install Yahoo Finance python library
  pip:
    name: yahoo-finance

- name: Copy stock price script
  copy:
    src: stock_price.py
    dest: /home/vagrant/stock_price.py
